name: Build and Deploy
on:
  push:
    branches:
      - main
jobs:
  deploy:
    name: Deploy Application
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@master
      - name: Create Node Envrironment
        uses: actions/setup-node@v1
        with:
          node-version: 12.x
      - name: Install Packages and Build Application
        run: |
          npm install
          npm run build
      - name: Deploy
        uses: s0/git-publish-subdir-action@develop
        env:
          REPO: self
          BRANCH: gh-pages
          FOLDER: public
          GITHUB_TOKEN: ${{ secrets.MY_GITHUB_TOKEN }}
